### ISSUE TITLE
error

### ISSUE THREAD

**Issue by demirklvc** [r0mar0ma/sd-webui-pez-dispenser#1]
Hello! thanks for creating this extension, been waiting for something like this a long time. i get this error when trying to generate a prompt:

Loading model: ViT-L-14:openai, device: GPU: NVIDIA GeForce RTX 3090 (24GB)

Traceback (most recent call last):
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-pez-dispenser\scripts\pez-dispenser.py", line 187, in inference
    prompt = utils.optimize_prompt(
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-pez-dispenser\common\optim_utils.py", line 246, in optimize_prompt
    all_target_features = get_target_feature(model, preprocess, tokenizer_funct, device, target_images=target_images, target_prompts=target_prompts)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-pez-dispenser\common\optim_utils.py", line 74, in get_target_feature
    curr_images = torch.concatenate(curr_images).to(device)
AttributeError: module 'torch' has no attribute 'concatenate'

**Comment by r0mar0ma** [comment]
Hi.

Could you check what torch version you have installed?
You can see it at the bottom of WebUI page.
Or a directory C:\Users\RTX01\stable-diffusion-webui\venv\Lib\site-packages\ **torch-X.X.X+cuXXX.dist-info**.

**Comment by demirklvc** [comment]
You are running torch 1.12.1+cu113.

**Comment by demirklvc** [comment]
@r0mar0ma

**Comment by r0mar0ma** [comment]
Sorry, it's a very old version, will not support it.
I'd recommend to upgrade to torch-1.13.1+cu117. Btw I suppose torch 1.13 will work faster than 1.12 on your RTX3090 (also don't forget to update cudnn files to latest version).

**Comment by demirklvc** [comment]
it wont break my auto install? im using an older version. if so: best way to update torch to that version?

**Comment by r0mar0ma** [comment]
In theory should not break. But I can't guarantee. Sometimes it's true - automatic1111 is breaking on upgrade.
In any case it makes a sense to use new version of webUI. Probably it's a good chance to move to the new one.

**Comment by demirklvc** [comment]
how could i update torch inside auto1111? @r0mar0ma

**Comment by r0mar0ma** [comment]
Use [Google power](https://www.google.com/search?q=automatic1111+update+torch)

**Comment by demirklvc** [comment]
but inside auto1111, no results found about this

**Comment by demirklvc** [comment]
torch 2 would be fitting?

**Comment by demirklvc** [comment]
@r0mar0ma

**Comment by r0mar0ma** [comment]
> torch 2 would be fitting?

yes
