### ISSUE TITLE
how to unload model

### ISSUE THREAD

**Issue by Kumakarym** [r0mar0ma/sd-webui-pez-dispenser#2]
hi 
how am i unload model, 
i cant found 

thx

**Comment by r0mar0ma** [comment]
Hi.
Good idea, I'll add a button.

**Comment by Kumakarym** [comment]
thanks i love the way you make this extension but after genearate prompts my a1111 is very slow I try use unload in other extension its not work lol 

and sorry for no good in English

**Comment by r0mar0ma** [comment]
Done.
Please check a ❌ button right of model selector.
It should unload model (if it was loaded before) and write a result in WebUI console.

Smth like:
Model unloaded, GPU memory freed: 3827.61 MB

**Comment by Kumakarym** [comment]
Nice Works , thank you for make this extension a few week ago i tried to code by use chatgpt because i just know python first time from A1111 haha  

by the way do you interest about ComfyUI

**Comment by r0mar0ma** [comment]
> by the way do you interest about ComfyUI

No, I'm not using and have no plans to use ComfyUI near future.
