### ISSUE TITLE
[Feature] XYZ grid or just X function to run all models

### ISSUE THREAD

**Issue by StableInfo** [r0mar0ma/sd-webui-pez-dispenser#3]
Hello,
It would be interesting to have an XYZ grid that let you run PEZ through different parameters values.
Especially being able to run through all the models.

Thanks.

(By the way, what is the difference between all models, and how to know which one to choose?)

**Comment by r0mar0ma** [comment]
Hi.

Currently there are no any plans to implement XYZ grids. Actually this extension is just a port of official [Hard Prompts Made Easy](https://github.com/YuxinWenRick/hard-prompts-made-easy) / [PEZ Dispenser](https://huggingface.co/spaces/tomg-group-umd/pez-dispenser) implementation with minimal revisions.

All models are pretrained [OpenCLIP](https://github.com/mlfoundations/open_clip) models.

The author of Hard Prompts Made Easy implementation says:
- clip_model: the name of the CLiP model for use with . "ViT-H-14" is the model used in SD 2.0 and Midjourney. "ViT-L-14" is the model used in SD 1.5. This should ideally match your target generator.
- clip_pretrain: the name of the pretrained model for [open_clip](https://github.com/mlfoundations/open_clip). For "ViT-H-14" use "laion2b_s32b_b79k". For "ViT-L-14" use "openai".
