### ISSUE TITLE
[FEATURE] batch of images

### ISSUE THREAD

**Issue by StableInfo** [r0mar0ma/sd-webui-pez-dispenser#4]
Hello
Thanks for the 5 insert images tabs available, 
What about being able to insert a path to a folder full of images, and being able to generate prompts for all of them?
Can this feature be implemented? thanks

**Comment by r0mar0ma** [comment]
Hi.

Multiple images are processing as one set to create combined single prompt. For example an image with a cat and an image with a woman will create some mix in result. You can read details [here](https://arxiv.org/abs/2302.03668).
In fact, as I see it works more or less normally for two-three images max. So no any sense to use folder with images as a source.

Batch processing will require a lot of redesign, probably later will implement this but not so soon.

**Comment by StableInfo** [comment]
Ah I was not aware, that is actually cool. Ok then put it in the "to do list later" list if you wish.
SInce I have you here, could you tell me how to know which "model" is best to use? What are the differences? What is the mindset /workglow when using pez here, what can we wish to achieve and how to achieve these different things, if there aremany methods/goals?

**Comment by r0mar0ma** [comment]
Please check neighbor thread about models. That is all what I know about them. Just playing with different models too and getting different results, but have no "right recipe".

**Comment by r0mar0ma** [comment]
Added folder batch processing in txt2img script section.
