### ISSUE TITLE
Not working in AUTOMATIC1111 v1.8.0

### ISSUE THREAD

**Issue by tndgpp** [r0mar0ma/sd-webui-pez-dispenser#5]
This extension does not work anymore in AUTOMATIC1111 WebUI v1.8.0. It does not install the requirement sentence_transformers package, as stated in WebUI logs:

`pez_dispenser error: No sentence_transformers package installed`

PEZ Dispenser tab in WebUI shows this error message:

![pez_dispenser_tab-min](https://github.com/r0mar0ma/sd-webui-pez-dispenser/assets/18227529/58ddeae0-3dfe-4fa5-84a5-2e598a44536f)

But restarting WebUI does not help. Not even manually installing sentence_transformers in WebUI env solves the problem.

**Comment by r0mar0ma** [comment]
Thanks, will check where is the problem soon.

**Comment by r0mar0ma** [comment]
@tndgpp Please check new version 1.4.1.

**Comment by tndgpp** [comment]
Version 1.4.1 solves the problem, tested it and all is fine. Thanks for the quick response!
